### Linear Algebra

In [1]:
import numpy as np

In [2]:
A = [[2, - 1], [0, 3]] 
B = [[1, 4], [- 2, 5]] 
c = 2
d = 3

In [4]:
v_A = np.array([[2, - 1], [0, 3]])
v_B = np.array([[1, 4], [- 2, 5]])

print(f"Matrix A:\n {v_A}")

print(f"Matrix B:\n {v_B}")

Matrix A:
 [[ 2 -1]
 [ 0  3]]
Matrix B:
 [[ 1  4]
 [-2  5]]


In [5]:
# Scalar Multiplication
scaled_A = c * v_A
scaled_B = d * v_B

print(f"Scaled Matrix A:\n {scaled_A}")
print(f"Scaled Matrix B:\n {scaled_B}")

Scaled Matrix A:
 [[ 4 -2]
 [ 0  6]]
Scaled Matrix B:
 [[ 3 12]
 [-6 15]]


In [7]:
# Verify the Scalar Multiplication Properties
# Associative: c(d*A) = (c*d)A
cd_A = (c * d) * v_A
c_dA = c * (d * v_A)

print(f"(c * d) * A = {cd_A}")
print(f"c * (d * A) = {c_dA}")
print(f"Associative: {np.array_equal(cd_A, c_dA)}")

(c * d) * A = [[12 -6]
 [ 0 18]]
c * (d * A) = [[12 -6]
 [ 0 18]]
Associative: True


In [9]:
# Distributive: c(A+B) = cA + cB
c_A_B = c * (v_A + v_B)
cA_cB = (c * v_A ) + (c* v_B)

print(f" c(A+B) = {c_A_B}")
print(f"cA + cB = {cA_cB}")
print(f"Distributive: {np.array_equal(c_A_B, cA_cB)}")

 c(A+B) = [[ 6  6]
 [-4 16]]
cA + cB = [[ 6  6]
 [-4 16]]
Distributive: True


In [ ]:
# Find the transpose of both matrices:
v_A = np.array([[2, - 1], [0, 3]])
print("\nTranspose A^T:")
print(v_A.T)


Transpose A^T:
[[ 2  0]
 [-1  3]]


In [11]:
v_B = np.array([[1, 4], [- 2, 5]])
print("\nTranspose B^T:")
print(v_B.T)


Transpose B^T:
[[ 1 -2]
 [ 4  5]]


In [12]:
#find inverse of the matrices
v_A = np.array([[2, - 1], [0, 3]])
print("\nInverse A^(-1):")
print(np.linalg.inv(v_A))


Inverse A^(-1):
[[0.5        0.16666667]
 [0.         0.33333333]]


In [13]:
v_B = np.array([[1, 4], [- 2, 5]])
print("\nInverse B^(-1):")
print(np.linalg.inv(v_B))


Inverse B^(-1):
[[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]


In [14]:
v_A = np.array([[2, - 1], [0, 3]])
print("\nDeterminant |A|:")
print(np.linalg.det(v_A))




Determinant |A|:
6.0


In [15]:
v_B = np.array([[1, 4], [- 2, 5]])
print("\nDeterminant |A|:")
print(np.linalg.det(v_B))



Determinant |A|:
13.0
