In [1]:
import numpy as np

Question 1:  Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

In [2]:
#Question 1
arr = np.random.randint(1, 50,(6,6))

print("The Original Array:",arr)

The Original Array: [[46  7 19 12 20 33]
 [42 31 24 48 18 11]
 [ 5 29 47  7 19 16]
 [31 33 40 36 36 21]
 [36 29  8 12  9 26]
 [15 19 28 24 32 46]]


Question 2: Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

In [11]:
print("The first two rows:", arr[:2, :])  
print("The last 3 columns:\n", arr[:, 3:])  
even_num = np.array(arr % 2 == 0)
print("Even Array:", arr[even_num])

TypeError: 'function' object is not subscriptable

Question 3: Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [4]:
arr2 = arr.reshape(3,2,6)
print("The Reshaped Array:",arr2)
flattened = arr2.flatten()                 
print("Flattened (copy):\n", flattened)


The Reshaped Array: [[[46  7 19 12 20 33]
  [42 31 24 48 18 11]]

 [[ 5 29 47  7 19 16]
  [31 33 40 36 36 21]]

 [[36 29  8 12  9 26]
  [15 19 28 24 32 46]]]
Flattened (copy):
 [46  7 19 12 20 33 42 31 24 48 18 11  5 29 47  7 19 16 31 33 40 36 36 21
 36 29  8 12  9 26 15 19 28 24 32 46]



Question 4: Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [5]:
arr_id = np.eye(4)
print("Identity matrix:\n",arr_id)
arr_diag = np.arange(10, 50, 10)
arr2_diag = np.diag(arr_diag)
print("Diagonal matrix:\n", arr2_diag)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


Question 5: Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [6]:
arr_3_4 = np.random.randint(1, 10,(3,4))
print("The 3 by 4 array:",arr_3_4)
arr_4_3= np.random.randint(1, 10,(4,3))
print("The 4 by 3 array:",arr_4_3)
print("Multiplication by mat mull:", np.matmul(arr_3_4, arr_4_3))


The 3 by 4 array: [[9 3 3 4]
 [1 9 2 9]
 [3 2 4 3]]
The 4 by 3 array: [[5 7 8]
 [6 7 5]
 [1 1 3]
 [1 9 6]]
Multiplication by mat mull: [[ 70 123 120]
 [ 70 153 113]
 [ 34  66  64]]


Question 6: Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [7]:
def arr():
     z = int(input("Enter the lower limit: "))
     u = int(input("Enter the upper limit: "))
     x = int(input("Enter the number of rows: "))
     y = int(input("Enter the number of coulmns: "))
     arrd_2D = np.random.randint(z, u,(x,y))
     print("Original Array:", arrd_2D)
     if arrd_2D.ndim == 2:
        arrd_2D_copy = arrd_2D.copy()
        square_mask = np.where(arrd_2D_copy %  2 == 0, np.square(arrd_2D_copy), arrd_2D_copy)
        odd_mask = np.where(square_mask % 2 != 0, -1, square_mask)
        return odd_mask
     else:
         print("Array not the right dimension")


arr()

Original Array: [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]], dtype=int32)

In [8]:
def arr():
   
     arrd_2D = np.random.randint(z, u,(x,y))
     print("Original Array:", arrd_2D)
     if arrd_2D.ndim == 2:
        arrd_2D_copy = arrd_2D.copy()
        square_mask = np.where(arrd_2D_copy %  2 == 0, np.square(arrd_2D_copy), arrd_2D_copy)
        odd_mask = np.where(square_mask % 2 != 0, -1, square_mask)
        return odd_mask
     else:
         print("Array not the right dimension")

In [13]:

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1, 2, 3, 4])
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
# 2D array indexing - row and column access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access specific element: [row, column]
print("Element at row 1, column 2:", arr2d[1, 2])        # 7

# Access entire rows or columns
print("First row:", arr2d[0, :])               # All columns of row 0
print("Second column:", arr2d[:, 1])           # All rows of column 1

# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2):\n", arr2d[1:3, 1:3])

Element at row 1, column 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray (rows 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]


In [15]:
arr3 = np.random.randint(1, 60,(6,6))
arr3

array([[14, 47, 10, 34,  2, 23],
       [51, 39, 38, 23, 38, 29],
       [24, 26, 47,  1, 24, 37],
       [18, 47, 49, 23, 53, 56],
       [28, 11, 12,  5, 44, 52],
       [ 6,  4, 54, 44, 29,  5]], dtype=int32)

In [20]:
arr3[:,4:]

array([[ 2, 23],
       [38, 29],
       [24, 37],
       [53, 56],
       [44, 52],
       [29,  5]], dtype=int32)

In [21]:
arr3[3,4]

np.int32(53)