
## CLASS TASK 2
## Given the following matrices:
``` ## A = [[2, - 1, 3], [0, 4, 1]] ```

``` ## B = [[1, 2], [- 2, 0], [5, - 3]] ```
## a Identify the number of rows and columns in each matrix.
## b Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.
## if the multiplication is defined, compute the resulting matrix.



## A
a1. for matrix A, the number of row is 2, while the number of column is 3 and the order of matrix is a 2 by 3 matrix

a2. for matrix B, the number of row is 3, while the number of colunm is 2 and the order of matrix is a 3 by 2 matrix

## B
Both  matrix can be multiplied

```  A = [[2, - 1, 3], [0, 4, 1]] ```

```  B = [[1, 2],[- 2, 0],[5, - 3]] ```

``` AB = [[19 -5],[-3,-3]] ```

``` BA = [[2, 7, 5],[-4, 2, -6],[10, -17, 12]] ```

In [1]:
import numpy as np

In [5]:
A = np.array([[2, - 1, 3], [0, 4, 1]])
B = np.array([[1, 2], [- 2, 0], [5, - 3]])
print(A)
print(B)
print("AB\n:", np.matmul(A, B))
print("BA\n:", np.matmul(B, A))

[[ 2 -1  3]
 [ 0  4  1]]
[[ 1  2]
 [-2  0]
 [ 5 -3]]
AB
: [[19 -5]
 [-3 -3]]
BA
: [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
